version: '3'
services:
    postgres:
        # Validar la version en docker hub
        image: 'postgres:latest'
        environment:
            POSTGRES_HOST_AUTH_METHOD: "trust"
    redis:
        # Validar la version en docker hub
        image: 'redis:latest'
    nginx:
        restart: always
        build: 
            dockerfile: Dockerfile.dev
            context: ./nginx
        depends_on:
                - api
                - client
        ports:
            - '3050:80'
    # Construcción local del servidor desde el folder server (api)
    api:        
        build:
            dockerfile: Dockerfile.dev 
            context: ./server
        volumes:
        # Carga todo en el folder asignado
            - .:/app/node_modules
        # Todo lo del servidor queda desplegado en este folder /app
            - ./server:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    # Construcción local del cliente desde el folder cliente
    client:
        stdin_open: true
        build: 
            dockerfile: Dockerfile.dev
            context: ./client
        volumes: 
            - .:/app/node_modules
            - ./client:/app
    # Construcción local del worker desde el folder worker
    worker:
        build: 
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes: 
            - .:/app/node_modules
            - ./worker:/app




